const CONNECT_EVENT			= 'CONNECT';
const DISCONNECT_EVENT	= 'DISCONNECT';
const ERROR_EVENT				= 'ERROR';
const SUBSCRIBE_EVENT		= 'HEY';
const UNSUBSCRIBE_EVENT	= 'BYE';

module.exports = {
	CONNECT_EVENT,
	DISCONNECT_EVENT,
	ERROR_EVENT,
	SUBSCRIBE_EVENT,
	UNSUBSCRIBE_EVENT,
};
